'use client'
import { useCallback, useEffect, useState } from 'react'
import { api } from '@/lib/api'
import { PageHeader, Badge, Spinner, Button, EmptyState, Card } from '@/components/ui'

/* Telegram post approval queue — mirrors dashboard/story-covers/page.tsx
 * exactly, applied to draft text instead of image candidates (migration 055 /
 * adminPostDrafts.ts).
 *
 * Every draft here was either queued on story publish or generated by the
 * weekly AI-scheduled job. Nothing reaches @koodakbook_app until تأیید is
 * clicked — that's the only action in the app that posts. */

type Status = 'pending' | 'approved' | 'rejected'

interface Draft {
  id: string
  source: 'story_published' | 'ai_scheduled' | 'manual'
  source_ref: string | null
  text: string
  status: Status
  created_at: string
  reviewed_at: string | null
  reviewed_by: string | null
  review_note: string | null
  posted_at: string | null
  post_result: string | null
}
interface Counts { pending: string; approved: string; rejected: string }

const TABS: { key: Status; label: string }[] = [
  { key: 'pending', label: 'در انتظار تأیید' },
  { key: 'approved', label: 'تأیید شده' },
  { key: 'rejected', label: 'رد شده' },
]
const SOURCE_LABEL: Record<Draft['source'], string> = {
  story_published: '📖 انتشار داستان',
  ai_scheduled: '🤖 تولید خودکار هوش مصنوعی',
  manual: '✍️ نوشته‌شده دستی',
}

export default function PostDraftsPage() {
  const [status, setStatus] = useState<Status>('pending')
  const [drafts, setDrafts] = useState<Draft[]>([])
  const [counts, setCounts] = useState<Counts | null>(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')
  const [busy, setBusy] = useState<Record<string, boolean>>({})
  const [rejecting, setRejecting] = useState<Record<string, string>>({})

  const load = useCallback(async (s: Status) => {
    setLoading(true); setError('')
    const res = await api.get<{ drafts: Draft[]; counts: Counts }>(`/api/admin/post-drafts/queue?status=${s}`)
    if (res.error) setError(res.error)
    else { setDrafts(res.data?.drafts ?? []); setCounts(res.data?.counts ?? null) }
    setLoading(false)
  }, [])

  useEffect(() => { void load(status) }, [status, load])

  const [generating, setGenerating] = useState(false)
  async function generateNow() {
    setGenerating(true)
    const res = await api.post<unknown>('/api/admin/post-drafts/generate', {})
    setGenerating(false)
    if (res.error) { setError(res.error); return }
    if (status === 'pending') void load('pending')
  }

  async function decide(id: string, decision: 'approved' | 'rejected', note?: string) {
    setBusy(b => ({ ...b, [id]: true }))
    const res = await api.post<Draft>(`/api/admin/post-drafts/${id}/review`, { decision, note })
    setBusy(b => ({ ...b, [id]: false }))
    if (res.error) { setError(res.error); return }
    setRejecting(r => { const { [id]: _drop, ...rest } = r; return rest })
    if (status === 'pending') {
      // Resolve in place — the card leaves this tab, the rest stay put.
      setDrafts(ds => ds.filter(d => d.id !== id))
      setCounts(c => c && {
        ...c,
        pending: String(Math.max(0, Number(c.pending) - 1)),
        [decision]: String(Number(c[decision]) + 1),
      } as Counts)
    } else if (res.data) {
      // A retry from the "approved" tab — update the card in place.
      setDrafts(ds => ds.map(d => (d.id === id ? res.data! : d)))
    }
  }

  return (
    <div className="space-y-6">
      <PageHeader
        title="صف تأیید تلگرام"
        subtitle="پیش‌نویس پست‌های کانال عمومی @koodakbook_app — تأیید تنها راهی است که چیزی منتشر می‌کند."
        actions={
          <div className="flex gap-2">
            <Button variant="secondary" disabled={generating} onClick={() => void generateNow()}>
              تولید محتوای هفتگی
            </Button>
            <Button variant="secondary" onClick={() => void load(status)}>تازه‌سازی</Button>
          </div>
        }
      />

      {counts && (
        <div className="grid grid-cols-3 gap-3">
          <Card className="p-4"><div className="text-2xl font-bold text-amber-600">{counts.pending}</div><div className="text-sm text-slate-500">در انتظار تأیید</div></Card>
          <Card className="p-4"><div className="text-2xl font-bold text-emerald-600">{counts.approved}</div><div className="text-sm text-slate-500">تأیید شده</div></Card>
          <Card className="p-4"><div className="text-2xl font-bold text-rose-600">{counts.rejected}</div><div className="text-sm text-slate-500">رد شده</div></Card>
        </div>
      )}

      <div className="flex gap-2">
        {TABS.map(t => (
          <button
            key={t.key}
            onClick={() => setStatus(t.key)}
            className={`px-4 py-2 rounded-lg text-sm font-medium transition ${
              status === t.key ? 'bg-amber-500 text-white' : 'bg-white text-slate-600 hover:bg-slate-100'
            }`}
          >{t.label}</button>
        ))}
      </div>

      {error && <div className="p-3 rounded-lg bg-rose-50 text-rose-700 text-sm">{error}</div>}

      {loading ? <Spinner /> : drafts.length === 0 ? (
        <EmptyState>
          {status === 'pending'
            ? 'هیچ پیش‌نویسی در انتظار تأیید نیست.'
            : 'موردی در این بخش نیست.'}
        </EmptyState>
      ) : (
        <div className="space-y-3">
          {drafts.map(d => {
            const sendFailed = d.status === 'approved' && d.post_result === 'error'
            return (
              <Card key={d.id} className="p-4 flex flex-col gap-3">
                <div className="flex flex-wrap items-center justify-between gap-2">
                  <div className="flex items-center gap-2">
                    <span className="text-sm font-bold text-slate-700">{SOURCE_LABEL[d.source]}</span>
                    {sendFailed && <Badge tone="red">ارسال نشد</Badge>}
                    {d.status === 'approved' && d.post_result === 'dry-run' && <Badge tone="amber">حالت آزمایشی — بدون توکن تلگرام</Badge>}
                  </div>
                  <span className="text-xs text-slate-400">{new Date(d.created_at).toLocaleString('fa-IR')}</span>
                </div>

                <p className="whitespace-pre-wrap text-sm text-slate-700 bg-slate-50 rounded-xl px-3 py-2" dir="rtl">
                  {d.text}
                </p>

                {d.review_note && (
                  <div className="text-xs text-rose-700 bg-rose-50 rounded p-2">دلیل رد: {d.review_note}</div>
                )}
                {d.reviewed_by && (
                  <div className="text-xs text-slate-400">بررسی‌شده توسط {d.reviewed_by}</div>
                )}

                {status === 'pending' && (
                  rejecting[d.id] !== undefined ? (
                    <div className="space-y-2">
                      <textarea
                        autoFocus
                        value={rejecting[d.id]}
                        onChange={e => setRejecting(r => ({ ...r, [d.id]: e.target.value }))}
                        placeholder="چرا این پیش‌نویس مناسب نیست؟"
                        rows={2}
                        className="w-full text-sm border border-slate-200 rounded-lg p-2 focus:outline-none focus:ring-2 focus:ring-rose-300"
                      />
                      <div className="flex gap-2">
                        <Button
                          variant="danger"
                          className="flex-1"
                          disabled={!rejecting[d.id]?.trim() || busy[d.id]}
                          onClick={() => void decide(d.id, 'rejected', rejecting[d.id].trim())}
                        >ثبت رد</Button>
                        <Button
                          variant="secondary"
                          onClick={() => setRejecting(r => { const { [d.id]: _drop, ...rest } = r; return rest })}
                        >انصراف</Button>
                      </div>
                    </div>
                  ) : (
                    <div className="flex gap-2">
                      <Button
                        className="flex-1"
                        disabled={busy[d.id]}
                        onClick={() => void decide(d.id, 'approved')}
                      >تأیید و ارسال</Button>
                      <Button
                        variant="secondary"
                        disabled={busy[d.id]}
                        onClick={() => setRejecting(r => ({ ...r, [d.id]: '' }))}
                      >رد</Button>
                    </div>
                  )
                )}

                {sendFailed && (
                  <Button disabled={busy[d.id]} onClick={() => void decide(d.id, 'approved')}>
                    تلاش دوباره برای ارسال
                  </Button>
                )}
              </Card>
            )
          })}
        </div>
      )}
    </div>
  )
}
