// Matches web's brand tokens (apps/web/src/app/globals.css: --ramp-brand-*)
// so the mobile app is the same saffron identity, not a placeholder. `primary`
// is the bright fill (buttons, active chips) -- text/icons drawn ON that fill
// use `onPrimary` (dark ink), never white: bg-amber-500/white measures ~2:1,
// well under the 4.5:1 floor (see design-review-2026-09-11.md). `onPrimary`
// doubles as the brand-colored TEXT color on light backgrounds (tab labels,
// links) for the same reason -- the bright tone is illegible as text on cream.
// `primaryDeep` is the pressed/bevel shade (web's --ramp-brand-deep).
export const colors = {
  bg: '#fdf6ec',
  card: '#ffffff',
  text: '#3b2f2f',
  muted: '#7a6a58',
  primary: '#FBBF24',
  onPrimary: '#654900',
  primaryDeep: '#745300',
  primarySoft: '#FEF3C7',
  success: '#22c55e',
  danger: '#dc2626',
  // Brand gradient (web's --color-brand-from/to) -- the single source-of-truth
  // 2-stop gradient for the hero/primary-action identity. Was drifting to a
  // 3-stop amber->orange gradient in places; kept to exactly these two stops
  // to match web (2026-09-17 parity pass).
  brandFrom: '#FBBF24',
  brandTo: '#F97316',
}

// Ported verbatim from web's `--ramp-*` custom properties
// (apps/web/src/app/globals.css, generated by tools/design/ramps.py --
// regenerate there, don't hand-edit a stop here either). Every content area
// gets its own 4-stop hue so a screen never has to invent an ad hoc pastel:
//   bright  the joyful saturated fill -- dark `ink` text sits here, never white
//   soft    pale tint -- chip/tile backgrounds, `ink` text sits here too
//   ink     icon/label/title colour on `bright` or `soft`
//   deep    3D edge / border / text-on-`soft`, and the only stop white text
//           may sit on
export const ramps = {
  brand:   { deep: '#745300', bright: '#FBBF24', soft: '#FEF3C7', ink: '#654900' },
  lessons: { deep: '#126547', bright: '#34D399', soft: '#ECFDF5', ink: '#0C4E36' },
  letters: { deep: '#015F89', bright: '#38BDF8', soft: '#F0F9FF', ink: '#004260' },
  phonics: { deep: '#914200', bright: '#FB923C', soft: '#FFF7ED', ink: '#612B00' },
  stories: { deep: '#10645A', bright: '#2DD4BF', soft: '#F0FDFA', ink: '#0B5048' },
  review:  { deep: '#561FFC', bright: '#A78BFA', soft: '#F5F3FF', ink: '#260099' },
  speak:   { deep: '#AE085F', bright: '#F472B6', soft: '#FDF2F8', ink: '#620235' },
  write:   { deep: '#056271', bright: '#22D3EE', soft: '#ECFEFF', ink: '#02505C' },
  math:    { deep: '#2337FA', bright: '#818CF8', soft: '#EEF2FF', ink: '#000D87' },
  games:   { deep: '#7600ED', bright: '#C084FC', soft: '#FAF5FF', ink: '#430087' },
  rewards: { deep: '#745300', bright: '#FBBF24', soft: '#FFFBEB', ink: '#654900' },
} as const

// Login = warm amber ("welcome back"), signup = fresh green ("start the
// adventure") -- same differentiation web's AuthShell.tsx uses so the two
// pages don't get mixed up.
export const auth = {
  login: { accent: '#F59E0B', accentDeep: '#B45309', bg: '#FFFBEB' },
  signup: { accent: '#10B981', accentDeep: '#047857', bg: '#ECFDF5' },
}

// web's --radius-* scale (globals.css), for anything that should read as the
// same "roundness" as a web card/button/chip rather than an arbitrary number.
export const radii = { sm: 12, md: 20, lg: 28, xl: 40, pill: 999 }

// web's --text-* type ladder, in px (web's rem values * 16). Not every screen
// needs every step -- pull what's relevant.
export const type = {
  display: 40, h1: 32, h2: 24, cardTitle: 20, body: 18, small: 15,
}

// Same face as web (next/font Vazirmatn) for body/UI text. RN picks weight by
// family name, not fontWeight, so each weight is its own family. `display` is
// web's `--font-baloo` (Baloo Bhaijaan 2) -- CHILD HEADINGS ONLY, never body
// text or the letter-being-taught glyph (DESIGN_CHARTER.md). Parent screens
// stay on Vazirmatn throughout, same as web's calmer parent app.
export const fonts = {
  regular: 'Vazirmatn_400Regular',
  medium: 'Vazirmatn_500Medium',
  bold: 'Vazirmatn_700Bold',
  display: 'BalooBhaijaan2_700Bold',
}
