'use client'

import { motion } from 'framer-motion'
import Link from 'next/link'
import type { CSSProperties, ReactNode } from 'react'
import { Icon, type IconName } from '@/components/icons'

/* ── Clay: the CHILD app's material ─────────────────────────────────────────
 *
 * Two registers, decided deliberately. The child app is clay — thick, coloured,
 * pressable, with an overshoot on release. The parent app stays flat and dense
 * (`.card`, `.shadow-card`, slate). A parent scanning progress at 11pm and a
 * five-year-old choosing a story are not the same user, and one surface cannot
 * serve both without patronising the adult or under-serving the child.
 *
 * This file owns the MATERIAL. `kit.tsx` owns the module VOCABULARY (which hue
 * means "stories") and builds on these. Nothing here knows what a module is.
 *
 * Every colour comes from a 4-stop ramp in globals.css (generated by
 * tools/design/ramps.py). DESIGN_CHARTER.md contract: `bright` is the joyful
 * saturated fill (Tailwind -400) and DARK `ink` text sits on it — never white.
 * White text is allowed only on `deep`. `ink` is solved to clear WCAG AA on
 * `bright` with headroom, so a clay surface cannot be built unreadable and the
 * cheerful colour never has to be darkened to make text pass.
 */

/** The ramps that exist. Adding one means adding it to tools/design/ramps.py
 *  and regenerating — not hand-writing a stop. */
export type Ramp =
  | 'brand' | 'lessons' | 'letters' | 'phonics' | 'stories'
  | 'review' | 'speak' | 'write' | 'math' | 'games' | 'rewards'

/** Feeds the `.clay` recipe its three colours. One recipe, eleven ramps.
 *  `ink` is the dark label colour that sits on `bright` — DESIGN_CHARTER.md:
 *  dark ink on the joyful fill, never white. */
export function clayVars(ramp: Ramp): CSSProperties {
  return {
    '--clay-fill': `var(--ramp-${ramp}-bright)`,
    '--clay-edge': `var(--ramp-${ramp}-deep)`,
    '--clay-ink': `var(--ramp-${ramp}-ink)`,
  } as CSSProperties
}

/** Ad-hoc clay hues for the few screens that deliberately want colour VARIETY
 *  within one module — the math rooms, the memory-game decks — rather than the
 *  single module hue. Each triple is fill (Tailwind -400) / edge (-700, the 3D
 *  edge + where white may sit) / ink (-950, the dark label), and every
 *  fill↔ink pair here clears WCAG AA (measured ≥ 6:1). Not a replacement for
 *  the module ramps — reach for this only when a screen's own spec asks for
 *  more than one colour. */
export type Tone =
  | 'emerald' | 'sky' | 'amber' | 'rose' | 'violet' | 'orange' | 'teal' | 'fuchsia' | 'lime'

const TONES: Record<Tone, [string, string, string]> = {
  emerald: ['#34D399', '#047857', '#022C22'],
  sky:     ['#38BDF8', '#0369A1', '#082F49'],
  amber:   ['#FBBF24', '#B45309', '#451A03'],
  rose:    ['#FB7185', '#BE123C', '#4C0519'],
  violet:  ['#A78BFA', '#6D28D9', '#2E1065'],
  orange:  ['#FB923C', '#C2410C', '#431407'],
  teal:    ['#2DD4BF', '#0F766E', '#042F2E'],
  fuchsia: ['#E879F9', '#A21CAF', '#4A044E'],
  lime:    ['#A3E635', '#4D7C0F', '#1A2E05'],
}

export function toneVars(tone: Tone): CSSProperties {
  const [fill, edge, ink] = TONES[tone]
  return { '--clay-fill': fill, '--clay-edge': edge, '--clay-ink': ink } as CSSProperties
}

const SPRING = { type: 'spring', stiffness: 500, damping: 20 } as const

/* ── Button ───────────────────────────────────────────────────────────────── */

type ButtonSize = 'sm' | 'md' | 'lg'

/* Sizes are floors, not paddings: 56px for a primary action, 48px for anything
 * in a list. Both come from NN/g's child touch-target research, and both are
 * above the 44px WCAG 2.5.8 minimum rather than exactly at it — a five-year-old
 * is not aiming, they are stabbing.
 *
 * DESIGN_CHARTER.md's floor for children is 56px, though — sm/md stay for
 * dense in-list rows where the row itself (not just the button) is the hit
 * target, but any button that IS the whole tap target uses `lg`. */
const BTN: Record<ButtonSize, string> = {
  sm: 'min-h-[40px] px-4 text-sm gap-1.5',
  md: 'min-h-[48px] px-5 text-base gap-2',
  lg: 'min-h-[56px] px-6 text-lg gap-2.5',
}

type ClayButtonProps = {
  children: ReactNode
  ramp?: Ramp
  size?: ButtonSize
  icon?: IconName
  href?: string
  onClick?: () => void
  disabled?: boolean
  type?: 'button' | 'submit'
  className?: string
  'aria-label'?: string
}

/** The one pressable thing in the child app. Renders as a link when given
 *  `href`, a button otherwise — so the affordance and the semantics never
 *  disagree (a Link styled as a button still has to be a link for the
 *  keyboard and the screen reader). */
export function ClayButton({
  children, ramp = 'brand', size = 'md', icon, href, onClick,
  disabled, type = 'button', className = '', ...rest
}: ClayButtonProps) {
  /* No text colour here: `.clay` sets `color: var(--clay-ink)` — dark ink on
   * the bright fill (DESIGN_CHARTER.md), and the disabled state overrides it. */
  const cls = `clay ${BTN[size]} inline-flex items-center justify-center font-bold w-full ${className}`
  const body = (
    <>
      {icon && <Icon name={icon} size={size === 'lg' ? 'lg' : 'md'} strokeWidth={2.4} />}
      {children}
    </>
  )

  if (href && !disabled) {
    return (
      <Link href={href} style={clayVars(ramp)} className={cls} {...rest}>
        {body}
      </Link>
    )
  }
  return (
    <button
      type={type} onClick={onClick} disabled={disabled}
      style={clayVars(ramp)} className={cls} {...rest}
    >
      {body}
    </button>
  )
}

/* ── Tile ─────────────────────────────────────────────────────────────────── */

type TileProps = {
  ramp: Ramp
  /** Override the module hue with an ad-hoc bright tone — for screens that
   *  deliberately want per-item colour variety (math rooms, game decks). */
  tone?: Tone
  icon: IconName
  /** The mark shown large on the tile face. Usually the module's colourful
   *  emoji (DESIGN_CHARTER.md — emoji carry section identity for a pre-reader),
   *  or the content the tile teaches (the Persian digit ۴ on the numerals
   *  room). `icon` stays required as the fall-back the locked state and the
   *  aria path use — a tile is never left without a glyph of some kind. */
  glyph?: string
  title: string
  sub?: string
  href: string
  big?: boolean
  locked?: boolean
  lockedHint?: string
}

/** The tappable activity tile. The press is the whole point: the tile travels
 *  down by exactly the thickness its edge loses, so the bottom stays planted
 *  and only the top face moves. Mismatch those two numbers and it reads as
 *  sliding rather than being pushed. */
export function ClayTile({
  ramp, tone, icon, glyph, title, sub, href, big, locked, lockedHint,
}: TileProps) {
  const pad = big ? 'p-5 min-h-[92px]' : 'p-4 min-h-[76px]'
  const vars = tone ? toneVars(tone) : clayVars(ramp)

  if (locked) {
    /* A locked tile keeps its shape so the grid doesn't reflow when it opens,
     * and drops every material cue so it never invites a tap it won't answer.
     * The warmth lives in the copy, not in the glyph — same call as the rest
     * of the app's locked states. */
    return (
      <div
        aria-disabled="true"
        aria-label={lockedHint ? `${title} — ${lockedHint}` : title}
        className={`clay ${pad} flex items-center gap-3`}
      >
        <Icon name="locked" size={big ? 'hero' : 'xl'} strokeWidth={2.2} />
        <div className="flex-1 min-w-0">
          <p className={`font-bold ${big ? 'text-lg' : 'text-[15px]'}`}>{title}</p>
          {lockedHint && <p className="text-xs mt-0.5 truncate">{lockedHint}</p>}
        </div>
      </div>
    )
  }

  return (
    <Link href={href} aria-label={sub ? `${title}: ${sub}` : title} className="block group">
      <motion.div
        whileTap={{ y: 4 }}
        transition={SPRING}
        style={vars}
        className={`clay relative overflow-hidden ${pad} flex items-center gap-3`}
      >
        {/* Toy-like sheen. Decorative: it reinforces the light direction the
            inset highlight already establishes, so the two agree. */}
        <span className="absolute -top-6 -left-6 w-20 h-20 bg-white/25 rounded-full" aria-hidden="true" />
        {glyph
          ? (
            <span
              className={`font-bold leading-none shrink-0 text-center ${big ? 'text-5xl w-12' : 'text-4xl w-9'}`}
              aria-hidden="true"
            >
              {glyph}
            </span>
          )
          : <Icon name={icon} size={big ? 'hero' : 'xl'} strokeWidth={2.2} />}
        <div className="flex-1 min-w-0">
          <p className={`font-bold ${big ? 'text-lg' : 'text-[15px]'}`}>{title}</p>
          {/* Full ink, not opacity-75 — the ramps' ink colour is tuned to
              clear AA at full strength; dropping opacity toward the fill
              colour pushed several bright/soft ramps below 4.5:1. */}
          {sub && <p className="text-xs font-medium truncate mt-0.5">{sub}</p>}
        </div>
      </motion.div>
    </Link>
  )
}

/** Square tile for horizontal carousels — same material, stacked layout.
 *  Pass `glyph` for the module's colourful emoji or the content the tile
 *  teaches (the Persian digit ۴ on the numerals room); pass `icon` for the
 *  small utility cases that want a Lucide glyph instead. */
export function ClayMiniTile({
  ramp, icon, glyph, title, href, big, inList, label,
}: {
  ramp: Ramp
  icon?: IconName
  glyph?: string
  title: string
  href: string
  /** The band-1 size: two of these ARE the whole menu for a 3–5 year old. */
  big?: boolean
  /** Only pass inside a role="list" — a stray listitem is invalid ARIA. */
  inList?: boolean
  label?: string
}) {
  return (
    <Link
      href={href}
      role={inList ? 'listitem' : undefined}
      aria-label={label ?? title}
      className={big ? 'group block' : 'flex-shrink-0 snap-start group'}
    >
      <motion.div
        whileTap={{ y: 4 }}
        transition={SPRING}
        style={clayVars(ramp)}
        className={`clay relative overflow-hidden flex flex-col items-center justify-center ${
          big ? 'w-full min-h-[136px] p-5 gap-2' : 'w-32 h-[120px] gap-1.5'
        }`}
      >
        <span
          className={`absolute bg-white/25 rounded-full ${
            big ? '-top-8 -left-8 w-24 h-24' : '-top-5 -left-5 w-16 h-16'
          }`}
          aria-hidden="true"
        />
        {icon
          ? <Icon name={icon} size={big ? 56 : 36} strokeWidth={2} />
          : <span className={`font-bold ${big ? 'text-6xl' : 'text-4xl'}`} aria-hidden="true">{glyph}</span>}
        <p className={`font-bold ${big ? 'text-xl' : 'text-sm'}`}>{title}</p>
      </motion.div>
    </Link>
  )
}

/* ── Bar ──────────────────────────────────────────────────────────────────── */

/** Progress. The fill animates from wherever it was, because the *movement*
 *  is the reward — a bar that simply appears at 60% tells a child nothing
 *  about what they just did. Reduced-motion callers get the same final state
 *  instantly (globals.css kills the duration wholesale). */
export function ClayBar({
  value, ramp = 'brand', label, showValue = false, className = '',
}: {
  value: number            // 0–100
  ramp?: Ramp
  label: string            // required: a bare bar is unlabelled to a screen reader
  showValue?: boolean
  className?: string
}) {
  const pct = Math.max(0, Math.min(100, Math.round(value)))
  return (
    <div className={className}>
      {showValue && (
        <div className="flex items-baseline justify-between mb-1.5">
          <span className="text-xs font-bold text-text-secondary">{label}</span>
          <span className="text-xs font-bold tabular-nums" style={{ color: `var(--ramp-${ramp}-ink)` }}>
            ٪{pct}
          </span>
        </div>
      )}
      <div
        role="progressbar"
        aria-valuenow={pct} aria-valuemin={0} aria-valuemax={100} aria-label={label}
        className="h-3 rounded-pill overflow-hidden"
        style={{ background: `var(--ramp-${ramp}-soft)` }}
      >
        <motion.div
          className="h-full rounded-pill"
          style={{ background: `var(--ramp-${ramp}-bright)` }}
          initial={{ width: 0 }}
          animate={{ width: `${pct}%` }}
          transition={{ duration: 0.6, ease: [0.22, 0.61, 0.36, 1] }}
        />
      </div>
    </div>
  )
}

/* ── Chip ─────────────────────────────────────────────────────────────────── */

/** Small labelled token: `soft` ground, `ink` text and glyph. That pairing is
 *  solved for AA in ramps.py, so a chip cannot be built unreadable. */
export function ClayChip({
  children, ramp = 'brand', icon, className = '',
}: {
  children: ReactNode; ramp?: Ramp; icon?: IconName; className?: string
}) {
  return (
    <span
      className={`inline-flex items-center gap-1.5 px-3 py-1.5 rounded-pill text-xs font-bold ${className}`}
      style={{
        background: `var(--ramp-${ramp}-soft)`,
        color: `var(--ramp-${ramp}-ink)`,
      }}
    >
      {icon && <Icon name={icon} size="xs" strokeWidth={2.4} />}
      {children}
    </span>
  )
}

/** Rounded-square identity chip: a module's colour on its `soft` tint. Shows
 *  the module's colourful emoji by default (DESIGN_CHARTER.md — emoji carry
 *  section identity for a child); pass `icon` for the small utility cases where
 *  a Lucide glyph is wanted instead, and it takes `currentColor` from the chip
 *  so the ramp still drives the tint. */
export function ClayIconChip({
  ramp, icon, glyph, size = 'md',
}: {
  ramp: Ramp; icon?: IconName; glyph?: string; size?: 'md' | 'lg' | 'xl'
}) {
  const box = size === 'xl' ? 'w-16 h-16 rounded-2xl'
    : size === 'lg' ? 'w-14 h-14 rounded-2xl'
      : 'w-12 h-12 rounded-xl'
  const iconSize = size === 'xl' ? 'xl' : size === 'lg' ? 'lg' : 'md'
  const emojiSize = size === 'xl' ? 'text-4xl' : size === 'lg' ? 'text-3xl' : 'text-2xl'
  return (
    <span
      className={`${box} flex items-center justify-center shrink-0`}
      style={{
        background: `var(--ramp-${ramp}-soft)`,
        color: `var(--ramp-${ramp}-ink)`,
      }}
      aria-hidden={glyph && !icon ? true : undefined}
    >
      {icon
        ? <Icon name={icon} size={iconSize} strokeWidth={2.2} />
        : <span className={`${emojiSize} leading-none`}>{glyph}</span>}
    </span>
  )
}
