'use client'

import { motion } from 'framer-motion'
import Link from 'next/link'
import type { CSSProperties, ReactNode } from 'react'
import { Icon, type IconName } from '@/components/icons'

/* ── Clay: the CHILD app's material ─────────────────────────────────────────
 *
 * Two registers, decided deliberately. The child app is clay — thick, coloured,
 * pressable, with an overshoot on release. The parent app stays flat and dense
 * (`.card`, `.shadow-card`, slate). A parent scanning progress at 11pm and a
 * five-year-old choosing a story are not the same user, and one surface cannot
 * serve both without patronising the adult or under-serving the child.
 *
 * This file owns the MATERIAL. `kit.tsx` owns the module VOCABULARY (which hue
 * means "stories") and builds on these. Nothing here knows what a module is.
 *
 * Every colour comes from a 4-stop ramp in globals.css (generated by
 * tools/design/ramps.py). The point of the ramps is that the failure mode is
 * unreachable: `bright` is the ONLY fill white text is allowed on, and it is
 * solved to clear WCAG AA with headroom. A component here never picks a hex or
 * a Tailwind number, so the 2026-09 audit's finding — white titles at ~2:1 on
 * a cheerful mid-tone — cannot recur by someone reaching for `-400` again.
 */

/** The ramps that exist. Adding one means adding it to tools/design/ramps.py
 *  and regenerating — not hand-writing a stop. */
export type Ramp =
  | 'brand' | 'lessons' | 'letters' | 'phonics' | 'stories'
  | 'review' | 'speak' | 'write' | 'math' | 'games' | 'rewards'

/** Feeds the `.clay` recipe its two colours. One recipe, eleven ramps. */
export function clayVars(ramp: Ramp): CSSProperties {
  return {
    '--clay-fill': `var(--ramp-${ramp}-bright)`,
    '--clay-edge': `var(--ramp-${ramp}-deep)`,
  } as CSSProperties
}

const SPRING = { type: 'spring', stiffness: 500, damping: 20 } as const

/* ── Button ───────────────────────────────────────────────────────────────── */

type ButtonSize = 'sm' | 'md' | 'lg'

/* Sizes are floors, not paddings: 56px for a primary action, 48px for anything
 * in a list. Both come from NN/g's child touch-target research, and both are
 * above the 44px WCAG 2.5.8 minimum rather than exactly at it — a five-year-old
 * is not aiming, they are stabbing. */
const BTN: Record<ButtonSize, string> = {
  sm: 'min-h-[40px] px-4 text-sm gap-1.5',
  md: 'min-h-[48px] px-5 text-base gap-2',
  lg: 'min-h-[56px] px-6 text-lg gap-2.5',
}

type ClayButtonProps = {
  children: ReactNode
  ramp?: Ramp
  size?: ButtonSize
  icon?: IconName
  href?: string
  onClick?: () => void
  disabled?: boolean
  type?: 'button' | 'submit'
  className?: string
  'aria-label'?: string
}

/** The one pressable thing in the child app. Renders as a link when given
 *  `href`, a button otherwise — so the affordance and the semantics never
 *  disagree (a Link styled as a button still has to be a link for the
 *  keyboard and the screen reader). */
export function ClayButton({
  children, ramp = 'brand', size = 'md', icon, href, onClick,
  disabled, type = 'button', className = '', ...rest
}: ClayButtonProps) {
  const cls = `clay ${BTN[size]} inline-flex items-center justify-center font-bold text-white w-full ${className}`
  const body = (
    <>
      {icon && <Icon name={icon} size={size === 'lg' ? 'lg' : 'md'} strokeWidth={2.4} />}
      {children}
    </>
  )

  if (href && !disabled) {
    return (
      <Link href={href} style={clayVars(ramp)} className={cls} {...rest}>
        {body}
      </Link>
    )
  }
  return (
    <button
      type={type} onClick={onClick} disabled={disabled}
      style={clayVars(ramp)} className={cls} {...rest}
    >
      {body}
    </button>
  )
}

/* ── Tile ─────────────────────────────────────────────────────────────────── */

type TileProps = {
  ramp: Ramp
  icon: IconName
  title: string
  sub?: string
  href: string
  big?: boolean
  locked?: boolean
  lockedHint?: string
}

/** The tappable activity tile. The press is the whole point: the tile travels
 *  down by exactly the thickness its edge loses, so the bottom stays planted
 *  and only the top face moves. Mismatch those two numbers and it reads as
 *  sliding rather than being pushed. */
export function ClayTile({
  ramp, icon, title, sub, href, big, locked, lockedHint,
}: TileProps) {
  const pad = big ? 'p-5 min-h-[92px]' : 'p-4 min-h-[76px]'

  if (locked) {
    /* A locked tile keeps its shape so the grid doesn't reflow when it opens,
     * and drops every material cue so it never invites a tap it won't answer.
     * The warmth lives in the copy, not in the glyph — same call as the rest
     * of the app's locked states. */
    return (
      <div
        aria-disabled="true"
        aria-label={lockedHint ? `${title} — ${lockedHint}` : title}
        className={`clay ${pad} flex items-center gap-3`}
      >
        <Icon name="locked" size={big ? 'hero' : 'xl'} strokeWidth={2.2} />
        <div className="flex-1 min-w-0">
          <p className={`font-bold ${big ? 'text-lg' : 'text-[15px]'}`}>{title}</p>
          {lockedHint && <p className="text-xs mt-0.5 truncate">{lockedHint}</p>}
        </div>
      </div>
    )
  }

  return (
    <Link href={href} aria-label={sub ? `${title}: ${sub}` : title} className="block group">
      <motion.div
        whileTap={{ y: 4 }}
        transition={SPRING}
        style={clayVars(ramp)}
        className={`clay relative overflow-hidden ${pad} flex items-center gap-3 text-white`}
      >
        {/* Toy-like sheen. Decorative: it reinforces the light direction the
            inset highlight already establishes, so the two agree. */}
        <span className="absolute -top-6 -left-6 w-20 h-20 bg-white/15 rounded-full" aria-hidden="true" />
        <Icon name={icon} size={big ? 'hero' : 'xl'} strokeWidth={2.2} className="drop-shadow-sm" />
        <div className="flex-1 min-w-0">
          <p className={`font-bold drop-shadow-sm ${big ? 'text-lg' : 'text-[15px]'}`}>{title}</p>
          {sub && <p className="text-xs text-white/85 truncate mt-0.5">{sub}</p>}
        </div>
      </motion.div>
    </Link>
  )
}

/** Square tile for horizontal carousels — same material, stacked layout.
 *  `glyph` is the escape hatch for the one case where the mark IS the content
 *  the tile teaches (the Persian digit ۴ on the numerals room); everything
 *  else passes an `icon` and gets the shared glyph set. */
export function ClayMiniTile({
  ramp, icon, glyph, title, href, big, inList, label,
}: {
  ramp: Ramp
  icon?: IconName
  glyph?: string
  title: string
  href: string
  /** The band-1 size: two of these ARE the whole menu for a 3–5 year old. */
  big?: boolean
  /** Only pass inside a role="list" — a stray listitem is invalid ARIA. */
  inList?: boolean
  label?: string
}) {
  return (
    <Link
      href={href}
      role={inList ? 'listitem' : undefined}
      aria-label={label ?? title}
      className={big ? 'group block' : 'flex-shrink-0 snap-start group'}
    >
      <motion.div
        whileTap={{ y: 4 }}
        transition={SPRING}
        style={clayVars(ramp)}
        className={`clay relative overflow-hidden flex flex-col items-center justify-center text-white ${
          big ? 'w-full min-h-[136px] p-5 gap-2' : 'w-32 h-[120px] gap-1.5'
        }`}
      >
        <span
          className={`absolute bg-white/15 rounded-full ${
            big ? '-top-8 -left-8 w-24 h-24' : '-top-5 -left-5 w-16 h-16'
          }`}
          aria-hidden="true"
        />
        {icon
          ? <Icon name={icon} size={big ? 56 : 36} strokeWidth={2} className="drop-shadow-sm" />
          : <span className={`font-bold drop-shadow-sm ${big ? 'text-6xl' : 'text-4xl'}`} aria-hidden="true">{glyph}</span>}
        <p className={`font-bold drop-shadow-sm ${big ? 'text-xl' : 'text-sm'}`}>{title}</p>
      </motion.div>
    </Link>
  )
}

/* ── Bar ──────────────────────────────────────────────────────────────────── */

/** Progress. The fill animates from wherever it was, because the *movement*
 *  is the reward — a bar that simply appears at 60% tells a child nothing
 *  about what they just did. Reduced-motion callers get the same final state
 *  instantly (globals.css kills the duration wholesale). */
export function ClayBar({
  value, ramp = 'brand', label, showValue = false, className = '',
}: {
  value: number            // 0–100
  ramp?: Ramp
  label: string            // required: a bare bar is unlabelled to a screen reader
  showValue?: boolean
  className?: string
}) {
  const pct = Math.max(0, Math.min(100, Math.round(value)))
  return (
    <div className={className}>
      {showValue && (
        <div className="flex items-baseline justify-between mb-1.5">
          <span className="text-xs font-bold text-text-secondary">{label}</span>
          <span className="text-xs font-bold tabular-nums" style={{ color: `var(--ramp-${ramp}-ink)` }}>
            ٪{pct}
          </span>
        </div>
      )}
      <div
        role="progressbar"
        aria-valuenow={pct} aria-valuemin={0} aria-valuemax={100} aria-label={label}
        className="h-3 rounded-pill overflow-hidden"
        style={{ background: `var(--ramp-${ramp}-soft)` }}
      >
        <motion.div
          className="h-full rounded-pill"
          style={{ background: `var(--ramp-${ramp}-bright)` }}
          initial={{ width: 0 }}
          animate={{ width: `${pct}%` }}
          transition={{ duration: 0.6, ease: [0.22, 0.61, 0.36, 1] }}
        />
      </div>
    </div>
  )
}

/* ── Chip ─────────────────────────────────────────────────────────────────── */

/** Small labelled token: `soft` ground, `ink` text and glyph. That pairing is
 *  solved for AA in ramps.py, so a chip cannot be built unreadable. */
export function ClayChip({
  children, ramp = 'brand', icon, className = '',
}: {
  children: ReactNode; ramp?: Ramp; icon?: IconName; className?: string
}) {
  return (
    <span
      className={`inline-flex items-center gap-1.5 px-3 py-1.5 rounded-pill text-xs font-bold ${className}`}
      style={{
        background: `var(--ramp-${ramp}-soft)`,
        color: `var(--ramp-${ramp}-ink)`,
      }}
    >
      {icon && <Icon name={icon} size="xs" strokeWidth={2.4} />}
      {children}
    </span>
  )
}

/** Rounded-square icon chip. The glyph takes `currentColor` from the chip, so
 *  a single ramp drives both the tint and the icon — the token behaviour the
 *  emoji it replaced could never express. */
export function ClayIconChip({
  ramp, icon, size = 'md',
}: {
  ramp: Ramp; icon: IconName; size?: 'md' | 'lg' | 'xl'
}) {
  const box = size === 'xl' ? 'w-16 h-16 rounded-2xl'
    : size === 'lg' ? 'w-14 h-14 rounded-2xl'
      : 'w-12 h-12 rounded-xl'
  const glyph = size === 'xl' ? 'xl' : size === 'lg' ? 'lg' : 'md'
  return (
    <span
      className={`${box} flex items-center justify-center shrink-0`}
      style={{
        background: `var(--ramp-${ramp}-soft)`,
        color: `var(--ramp-${ramp}-ink)`,
      }}
    >
      <Icon name={icon} size={glyph} strokeWidth={2.2} />
    </span>
  )
}
