#!/usr/bin/env python3
"""Derive 4-stop ramps (deep / bright / soft / ink) for KoodakBook.

Each hue is anchored on the EXISTING brand/module hue (decision: re-ramp the
amber brand, don't replace the palette). We keep H, choose S per stop, and
SOLVE for L so each stop hits a stated WCAG target instead of guessing.

Contract per ramp:
  bright : the saturated fill. WHITE text sits on it   -> >= 4.5:1 vs #FFF
  deep   : the 3D bottom edge / border. Must read as *darker than bright*
           and also work as text on `soft`                -> >= 7:1 vs #FFF
  soft   : the pale tint (chip bg, tile image area)       -> <= 1.25:1 vs #FFF
  ink    : icon/label color used ON soft                  -> >= 4.5:1 vs soft
"""
import colorsys

def srgb_to_lin(c):
    c = c / 255
    return c / 12.92 if c <= 0.04045 else ((c + 0.055) / 1.055) ** 2.4

def lum(rgb):
    r, g, b = (srgb_to_lin(c) for c in rgb)
    return 0.2126 * r + 0.7152 * g + 0.0722 * b

def ratio(a, b):
    la, lb = lum(a), lum(b)
    hi, lo = max(la, lb), min(la, lb)
    return (hi + 0.05) / (lo + 0.05)

def hsl(h, s, l):
    r, g, b = colorsys.hls_to_rgb(h / 360, l, s)
    return (round(r * 255), round(g * 255), round(b * 255))

def hexs(rgb):
    return '#%02X%02X%02X' % rgb

WHITE = (255, 255, 255)
# The child app never actually sits on pure white — .child-bg is a warm
# gradient and --color-warm-white is the body. Check the worst (darkest) end
# of that ground too, or the audit passes on a surface the app doesn't have.
WARM = (0xFF, 0xF5, 0xE0)   # darkest stop of .child-bg

def solve_l(h, s, target, against, lo=0.0, hi=1.0, mode='at_least'):
    """Binary-search lightness for the LIGHTEST colour meeting the target."""
    best = None
    for _ in range(40):
        mid = (lo + hi) / 2
        c = hsl(h, s, mid)
        ok = ratio(c, against) >= target
        if ok:
            best = mid
            lo = mid          # try lighter
        else:
            hi = mid
    return best if best is not None else lo

def solve_soft(h, s, max_ratio):
    """Lightest-but-still-tinted pale stop: darkest L whose contrast vs white
    stays under max_ratio (so it still reads as a tint, not a flat white)."""
    lo, hi = 0.0, 1.0
    best = hi
    for _ in range(40):
        mid = (lo + hi) / 2
        if ratio(hsl(h, s, mid), WHITE) <= max_ratio:
            best = mid
            hi = mid          # try darker
        else:
            lo = mid
    return best

# name -> (hue, sat_bright, sat_deep, sat_soft, sat_ink)
HUES = {
    'brand':   (36,  0.82, 0.86, 0.85, 0.86),   # saffron — the existing brand
    'lessons': (152, 0.62, 0.70, 0.62, 0.72),   # emerald
    'letters': (203, 0.68, 0.74, 0.70, 0.76),   # persian blue
    'phonics': (22,  0.78, 0.82, 0.82, 0.84),   # burnt orange
    'stories': (172, 0.62, 0.70, 0.62, 0.72),   # teal
    'review':  (272, 0.52, 0.58, 0.62, 0.60),   # violet
    'speak':   (338, 0.66, 0.70, 0.72, 0.72),   # pomegranate pink
    'write':   (190, 0.72, 0.80, 0.70, 0.82),   # cyan
    'math':    (232, 0.52, 0.58, 0.62, 0.60),   # indigo
    'games':   (286, 0.52, 0.58, 0.62, 0.60),   # purple
    'rewards': (43,  0.86, 0.88, 0.88, 0.90),   # gold
}

print(f"{'ramp':9} {'deep':8} {'bright':8} {'soft':8} {'ink':8}  "
      f"{'wht/brt':>7} {'deep/wht':>8} {'soft/wht':>8} {'ink/soft':>8} {'deep/soft':>9} "
      f"{'deep/warm':>9} {'ink/warm':>8}")
print('-' * 122)

out = {}
for name, (h, sb, sd, ss, si) in HUES.items():
    # Targets carry deliberate headroom over the AA floors (4.5 / 3.0). Solving
    # *to* 4.5 lands every stop at 4.50–4.55, which survives the audit and
    # nothing else: sub-pixel AA, a soft shadow bleeding under the glyph, or a
    # tile drawn on --color-warm-white rather than pure white all eat the
    # margin. 5.4 keeps a stop usable after the real world touches it.
    lb = solve_l(h, sb, 5.4, WHITE)             # bright: white text, AA + headroom
    ld = solve_l(h, sd, 8.0, WHITE)             # deep: edge/border, clearly darker
    ls = solve_soft(h, ss, 1.16)                # soft: a real tint, barely off white
    soft = hsl(h, ss, ls)
    li = solve_l(h, si, 5.4, soft)              # ink: AA + headroom on its own soft
    bright, deep, ink = hsl(h, sb, lb), hsl(h, sd, ld), hsl(h, si, li)
    out[name] = (deep, bright, soft, ink)
    print(f"{name:9} {hexs(deep):8} {hexs(bright):8} {hexs(soft):8} {hexs(ink):8}  "
          f"{ratio(bright, WHITE):7.2f} {ratio(deep, WHITE):8.2f} "
          f"{ratio(soft, WHITE):8.2f} {ratio(ink, soft):8.2f} {ratio(deep, soft):9.2f} "
          f"{ratio(deep, WARM):9.2f} {ratio(ink, WARM):8.2f}")

print()
print('/* generated by tools ramps.py — do not hand-edit stops */')
for name, (deep, bright, soft, ink) in out.items():
    print(f"  --color-{name}-deep:   {hexs(deep)};")
    print(f"  --color-{name}-bright: {hexs(bright)};")
    print(f"  --color-{name}-soft:   {hexs(soft)};")
    print(f"  --color-{name}-ink:    {hexs(ink)};")
